# Generated by Django 5.2.5 on 2025-08-20 11:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_permission', models.CharField(choices=[('view_transaction', 'Voir les transactions'), ('add_transaction', 'Ajouter des transactions'), ('change_transaction', 'Modifier les transactions'), ('delete_transaction', 'Supprimer les transactions'), ('view_recette', 'Voir les recettes'), ('add_recette', 'Ajouter des recettes'), ('change_recette', 'Modifier les recettes'), ('delete_recette', 'Supprimer les recettes'), ('view_depense', 'Voir les dépenses'), ('add_depense', 'Ajouter des dépenses'), ('change_depense', 'Modifier les dépenses'), ('delete_depense', 'Supprimer les dépenses'), ('view_tarif', 'Voir les tarifs'), ('change_tarif', 'Modifier les tarifs'), ('manage_remise', 'Gérer les remises'), ('view_rapport_journalier', 'Voir rapport journalier'), ('view_rapport_mensuel', 'Voir rapport mensuel'), ('view_statistiques', 'Voir les statistiques'), ('export_data', 'Exporter les données'), ('manage_users', 'Gérer les utilisateurs'), ('manage_permissions', 'Gérer les permissions'), ('manage_system', 'Gérer le système')], max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(help_text='Module concerné (transaction, recette, etc.)', max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'code_permission'],
            },
        ),
        migrations.CreateModel(
            name='TarifService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(help_text='Nom unique du service', max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('INTERNET', 'Services Internet'), ('MULTISERVICE', 'Multiservices'), ('VENTE', 'Vente de produits'), ('AUTRE', 'Autres services')], max_length=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix en Ariary', max_digits=8)),
                ('unite_mesure', models.CharField(default='unité', help_text='Unité de mesure (page, heure, pièce, etc.)', max_length=50)),
                ('type_papier', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3'), ('BRISTOL', 'Bristol'), ('AUTRE', 'Autre type')], help_text="Type de papier pour les services d'impression/photocopie", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('code_service', models.CharField(blank=True, help_text='Code unique pour identifier le service', max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif de service',
                'verbose_name_plural': 'Tarifs des services',
                'ordering': ['categorie', 'nom_service'],
            },
        ),
        migrations.CreateModel(
            name='TypePapier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du type de papier (ex: A4 N&B, A3 Couleur)', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Code unique (ex: A4_NB, A3_COULEUR)', max_length=20, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix par page/unité', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('actif', models.BooleanField(default=True, help_text='Type de papier disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de papier',
                'verbose_name_plural': 'Types de papier',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de transaction',
                'verbose_name_plural': 'Types de transactions',
            },
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('symbole', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('reference', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Gestion.categorieproduit', verbose_name='Catégorie')),
                ('unite_mesure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='Gestion.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('couleur', models.CharField(default='#007bff', help_text="Couleur hexadécimale pour l'interface", max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='Gestion.permission')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('heure_debut_travail', models.TimeField(blank=True, null=True)),
                ('heure_fin_travail', models.TimeField(blank=True, null=True)),
                ('jours_travail', models.CharField(default='1,2,3,4,5,6,7', help_text='Jours de la semaine (1=Lundi, 7=Dimanche) séparés par des virgules', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('permissions_refusees', models.ManyToManyField(blank=True, help_text='Permissions explicitement refusées même si dans le rôle', related_name='utilisateurs_refuses', to='Gestion.permission')),
                ('permissions_supplementaires', models.ManyToManyField(blank=True, help_text='Permissions en plus de celles du rôle', related_name='utilisateurs_supplementaires', to='Gestion.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.role')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, help_text='Quantité actuellement en stock', max_digits=10)),
                ('quantite_minimale', models.DecimalField(decimal_places=2, default=0, help_text="Seuil d'alerte pour réapprovisionnement", max_digits=10)),
                ('quantite_maximale', models.DecimalField(decimal_places=2, default=0, help_text='Capacité maximale de stockage', max_digits=10)),
                ('etat', models.CharField(choices=[('EN_STOCK', 'En stock'), ('RUPTURE', 'Rupture de stock'), ('COMMANDE', 'En commande'), ('LIMITE', 'Stock limité')], default='EN_STOCK', help_text='État actuel du stock', max_length=20)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Gestion.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['produit__designation'],
            },
        ),
        migrations.CreateModel(
            name='PalierRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_minimum', models.DecimalField(decimal_places=2, help_text='Quantité minimum pour bénéficier de cette remise', max_digits=8)),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT_FIXE', 'Montant fixe'), ('PRIX_UNITAIRE', 'Nouveau prix unitaire')], default='POURCENTAGE', max_length=15)),
                ('valeur_remise', models.DecimalField(decimal_places=2, help_text='Valeur de la remise (%, montant ou nouveau prix)', max_digits=8)),
                ('description', models.CharField(blank=True, help_text="Description de l'offre (ex: 'Remise volume pour impression')", max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('tarif_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_remise', to='Gestion.tarifservice')),
            ],
            options={
                'verbose_name': 'Palier de remise',
                'verbose_name_plural': 'Paliers de remise',
                'ordering': ['tarif_service', 'quantite_minimum'],
                'unique_together': {('tarif_service', 'quantite_minimum')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Gestion.categorieservice')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='ServicePersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, help_text='Quantité ou durée du service', max_digits=8)),
                ('prix_unitaire_original', models.DecimalField(decimal_places=2, help_text='Prix unitaire original du tarif', max_digits=8)),
                ('prix_unitaire_utilise', models.DecimalField(decimal_places=2, help_text='Prix unitaire utilisé après remises', max_digits=8)),
                ('details_supplementaires', models.TextField(blank=True, help_text='Détails spécifiques à cette utilisation du service')),
                ('remise_appliquee', models.ForeignKey(blank=True, help_text='Remise appliquée si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='Gestion.palierremise')),
                ('tarif_service', models.ForeignKey(help_text='Service utilisé', on_delete=django.db.models.deletion.PROTECT, related_name='utilisations', to='Gestion.tarifservice')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_personnalise', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Service personnalisé',
                'verbose_name_plural': 'Services personnalisés',
            },
        ),
        migrations.CreateModel(
            name='RecetteMultiservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('IMPRESSION', 'Impression'), ('PHOTOCOPIE', 'Photocopie'), ('RELIURE', 'Reliure'), ('PLASTIFICATION', 'Plastification'), ('SCAN', 'Numérisation'), ('AUTRE', 'Autre service')], max_length=15)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_papier', models.CharField(blank=True, choices=[('A4_NB', 'A4 N&B'), ('A4_COULEUR', 'A4 Couleur'), ('A3_NB', 'A3 N&B'), ('A3_COULEUR', 'A3 Couleur'), ('BRISTOL', 'Bristol'), ('AUTRE', 'Autre type')], help_text='Type de papier utilisé (requis pour impression/photocopie)', max_length=20)),
                ('papier_personnalise', models.CharField(blank=True, help_text="Nom du papier si 'Autre' est sélectionné", max_length=50)),
                ('nombre_pages', models.IntegerField(blank=True, help_text='Nombre de pages (obsolète, utiliser quantite)', null=True)),
                ('details', models.TextField(blank=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recette_multiservice', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Recette Multiservice',
                'verbose_name_plural': 'Recettes Multiservice',
            },
        ),
        migrations.CreateModel(
            name='RecetteInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_forfait', models.CharField(choices=[('HEURE', "À l'heure"), ('JOURNEE', 'Forfait journée'), ('SEMAINE', 'Forfait semaine'), ('MOIS', 'Forfait mensuel')], max_length=10)),
                ('duree_minutes', models.IntegerField(help_text='Durée en minutes')),
                ('poste_utilise', models.CharField(blank=True, max_length=50)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recette_internet', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Recette Internet',
                'verbose_name_plural': 'Recettes Internet',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', "Ajustement d'inventaire"), ('PERTE', 'Perte/Détérioration'), ('RETOUR', 'Retour de marchandise')], max_length=15)),
                ('motif', models.CharField(choices=[('ACHAT', 'Achat de marchandise'), ('VENTE', 'Vente/Utilisation'), ('IMPRESSION', 'Consommation pour impression'), ('PHOTOCOPIE', 'Consommation pour photocopie'), ('INVENTAIRE', "Correction d'inventaire"), ('DETERIORATION', 'Détérioration du produit'), ('VOL', 'Vol/Perte'), ('RETOUR_CLIENT', 'Retour client'), ('RETOUR_FOURNISSEUR', 'Retour fournisseur'), ('AUTRE', 'Autre motif')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité du mouvement', max_digits=10)),
                ('quantite_avant', models.DecimalField(decimal_places=2, help_text='Quantité en stock avant le mouvement', max_digits=10)),
                ('quantite_apres', models.DecimalField(decimal_places=2, help_text='Quantité en stock après le mouvement', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire pour ce mouvement', max_digits=8)),
                ('valeur_totale', models.DecimalField(decimal_places=2, default=0, help_text='Valeur totale du mouvement', max_digits=10)),
                ('numero_facture', models.CharField(blank=True, help_text="N° facture d'achat/vente", max_length=50)),
                ('fournisseur', models.CharField(blank=True, help_text='Fournisseur pour les achats', max_length=100)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire/Remarques')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='Gestion.stock')),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction associée si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_depense', models.CharField(choices=[('ELECTRICITE', 'Électricité'), ('INTERNET', 'Connexion Internet'), ('MAINTENANCE', 'Maintenance équipements'), ('FOURNITURES', 'Fournitures de bureau'), ('SALAIRE', 'Salaires'), ('LOYER', 'Loyer'), ('AUTRE', 'Autre dépense')], max_length=15)),
                ('fournisseur', models.CharField(blank=True, max_length=100)),
                ('numero_facture', models.CharField(blank=True, max_length=50)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depense', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité vendue', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire de vente', max_digits=8)),
                ('produit', models.ForeignKey(help_text='Produit vendu', on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='Gestion.produit')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vente_produit', to='Gestion.transaction')),
            ],
            options={
                'verbose_name': 'Vente de produit',
                'verbose_name_plural': 'Ventes de produits',
            },
        ),
    ]
