# Generated by Django 5.2.5 on 2025-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePapier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du type de papier (ex: A4 N&B, A3 Couleur)', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Code unique (ex: A4_NB, A3_COULEUR)', max_length=20, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, help_text='Prix par page/unité', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle')),
                ('actif', models.BooleanField(default=True, help_text='Type de papier disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de papier',
                'verbose_name_plural': 'Types de papier',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='recettemultiservice',
            name='papier_personnalise',
            field=models.CharField(blank=True, help_text="Nom du papier si 'Autre' est sélectionné", max_length=50),
        ),
        migrations.AlterField(
            model_name='recettemultiservice',
            name='nombre_pages',
            field=models.IntegerField(blank=True, help_text='Nombre de pages (obsolète, utiliser quantite)', null=True),
        ),
        migrations.AlterField(
            model_name='recettemultiservice',
            name='type_papier',
            field=models.CharField(blank=True, choices=[('A4_NB', 'A4 N&B'), ('A4_COULEUR', 'A4 Couleur'), ('A3_NB', 'A3 N&B'), ('A3_COULEUR', 'A3 Couleur'), ('BRISTOL', 'Bristol'), ('AUTRE', 'Autre type')], help_text='Type de papier utilisé (requis pour impression/photocopie)', max_length=20),
        ),
    ]
