# Generated by Django 5.0.6 on 2024-05-21 13:30

from django.db import migrations

def seed_product_categories(apps, schema_editor):
    """
    Ajoute les catégories de produits initiales.
    """
    CategorieProduit = apps.get_model('Gestion', 'CategorieProduit')
    
    categories = [
        {
            "nom": "Papeterie",
            "description": "Tous les types de papier et supports d'impression."
        },
        {
            "nom": "Consommables d'Impression",
            "description": "Cartouches d'encre et toners pour imprimantes."
        },
        {
            "nom": "Fournitures de Reliure et Finition",
            "description": "Articles utilisés pour les services de reliure, plastification, etc."
        }
    ]

    for cat_data in categories:
        CategorieProduit.objects.get_or_create(nom=cat_data["nom"], defaults=cat_data)

class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'), # Assurez-vous que le nom correspond à votre première migration
    ]

    operations = [
        migrations.RunPython(seed_product_categories),
    ]
