# Generated by Django 5.0.6 on 2024-05-21 14:05

from django.db import migrations

def seed_unite_mesure(apps, schema_editor):
    """
    Ajoute les unités de mesure initiales.
    """
    UniteMesure = apps.get_model('Gestion', 'UniteMesure')
    
    unites = [
        {'nom': 'Pièce', 'symbole': 'pce', 'description': 'Unité pour un article individuel.'},
        {'nom': 'Feuille', 'symbole': 'feuille', 'description': 'Unité pour une seule feuille de papier.'},
        {'nom': 'Rame', 'symbole': 'rame', 'description': 'Un paquet de feuilles de papier (souvent 500).'},
        {'nom': 'Paquet', 'symbole': 'paquet', 'description': 'Un emballage contenant plusieurs articles.'},
        {'nom': 'Cartouche', 'symbole': 'cart.', 'description': "Unité pour les cartouches d'encre ou toners."},
        {'nom': 'Bouteille', 'symbole': 'bout.', 'description': "Pour les recharges d'encre liquide."},
        {'nom': 'Unité', 'symbole': 'unité', 'description': 'Unité générique par défaut.'},
    ]

    for unite_data in unites:
        UniteMesure.objects.get_or_create(nom=unite_data["nom"], defaults=unite_data)

class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_seed_product_categories'), # Dépend de la migration précédente pour les catégories
    ]

    operations = [
        migrations.RunPython(seed_unite_mesure),
    ]
