# Generated by Django 5.2.5 on 2025-11-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_seed_unite_mesure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='Mon Cyber', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('default_currency', models.CharField(default='Ar', help_text='Devise par défaut (ex: Ar, EUR, USD)', max_length=10)),
                ('default_stock_alert_threshold', models.DecimalField(decimal_places=2, default=5, help_text="Seuil d'alerte de stock par défaut pour les nouveaux produits", max_digits=10)),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
        migrations.RemoveField(
            model_name='recettemultiservice',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='recettemultiservice',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='historicaltarifservice',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='tarifservice',
            name='type_papier',
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(choices=[('ACHAT', 'Achat de marchandise'), ('VENTE', 'Vente/Utilisation'), ('IMPRESSION', 'Consommation pour impression'), ('PHOTOCOPIE', 'Consommation pour photocopie'), ('UTILISATION_SERVICE', 'Utilisation pour un service'), ('INVENTAIRE', "Correction d'inventaire"), ('DETERIORATION', 'Détérioration du produit'), ('VOL', 'Vol/Perte'), ('RETOUR_CLIENT', 'Retour client'), ('RETOUR_FOURNISSEUR', 'Retour fournisseur'), ('AUTRE', 'Autre motif')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConsommationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, help_text='Quantité de produit consommée pour UNE unité du service.', max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.produit')),
                ('tarif_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tarifservice')),
            ],
            options={
                'verbose_name': 'Consommation de produit par service',
                'verbose_name_plural': 'Consommations de produits par service',
                'unique_together': {('tarif_service', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='tarifservice',
            name='produits_consommes',
            field=models.ManyToManyField(blank=True, related_name='services_consommateurs', through='Gestion.ConsommationService', to='Gestion.produit'),
        ),
        migrations.DeleteModel(
            name='RecetteInternet',
        ),
        migrations.DeleteModel(
            name='RecetteMultiservice',
        ),
    ]
