# Generated by Django 5.2.5 on 2025-11-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_seed_unite_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltarifservice',
            name='produit_consomme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Produit consommé par ce service (ex: papier pour l'impression)", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gestion.produit'),
        ),
        migrations.AddField(
            model_name='tarifservice',
            name='produit_consomme',
            field=models.ForeignKey(blank=True, help_text="Produit consommé par ce service (ex: papier pour l'impression)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_consommateurs', to='Gestion.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(choices=[('ACHAT', 'Achat de marchandise'), ('VENTE', 'Vente/Utilisation'), ('IMPRESSION', 'Consommation pour impression'), ('PHOTOCOPIE', 'Consommation pour photocopie'), ('UTILISATION_SERVICE', 'Utilisation pour un service'), ('INVENTAIRE', "Correction d'inventaire"), ('DETERIORATION', 'Détérioration du produit'), ('VOL', 'Vol/Perte'), ('RETOUR_CLIENT', 'Retour client'), ('RETOUR_FOURNISSEUR', 'Retour fournisseur'), ('AUTRE', 'Autre motif')], max_length=20),
        ),
    ]
