# Generated by Django 5.0.4 on 2025-12-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_parametreentreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevente',
            name='usage_interne',
            field=models.BooleanField(default=False, help_text='Cochez si cette ligne est pour un usage interne (pas de recette, mais déstockage)'),
        ),
        migrations.AddField(
            model_name='servicepersonnalise',
            name='usage_interne',
            field=models.BooleanField(default=False, help_text='Cochez si ce service est pour un usage interne (pas de recette, mais déstockage)'),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='usage_interne',
            field=models.BooleanField(default=False, help_text='Cochez si ce produit est pour un usage interne (pas de recette, mais déstockage)'),
        ),
    ]
