# Generated by Django 5.2.5 on 2025-11-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_historicaltarifservice_produit_consomme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltarifservice',
            name='produit_consomme',
        ),
        migrations.RemoveField(
            model_name='tarifservice',
            name='produit_consomme',
        ),
        migrations.CreateModel(
            name='ConsommationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, help_text='Quantité de produit consommée pour UNE unité du service.', max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.produit')),
                ('tarif_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.tarifservice')),
            ],
            options={
                'verbose_name': 'Consommation de produit par service',
                'verbose_name_plural': 'Consommations de produits par service',
                'unique_together': {('tarif_service', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='tarifservice',
            name='produits_consommes',
            field=models.ManyToManyField(blank=True, related_name='services_consommateurs', through='Gestion.ConsommationService', to='Gestion.produit'),
        ),
    ]
