# Generated by Django 5.2.8 on 2025-12-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_lignedevente_usage_interne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code_permission',
            field=models.CharField(choices=[('view_transaction', 'Voir les transactions'), ('add_transaction', 'Ajouter des transactions'), ('change_transaction', 'Modifier les transactions'), ('delete_transaction', 'Supprimer les transactions'), ('view_recette', 'Voir les recettes'), ('add_recette', 'Ajouter des recettes'), ('change_recette', 'Modifier les recettes'), ('delete_recette', 'Supprimer les recettes'), ('view_depense', 'Voir les dépenses'), ('add_depense', 'Ajouter des dépenses'), ('change_depense', 'Modifier les dépenses'), ('delete_depense', 'Supprimer les dépenses'), ('view_tarif', 'Voir les tarifs'), ('change_tarif', 'Modifier les tarifs'), ('manage_remise', 'Gérer les remises'), ('view_produit', 'Voir les produits'), ('add_produit', 'Ajouter des produits'), ('change_produit', 'Modifier des produits'), ('delete_produit', 'Supprimer des produits'), ('view_stock', 'Voir les stocks'), ('add_stock', 'Ajouter du stock (Entrées/Achats)'), ('change_stock', 'Modifier/Ajuster le stock'), ('delete_stock', 'Supprimer le stock'), ('view_rapport_journalier', 'Voir rapport journalier'), ('view_rapport_mensuel', 'Voir rapport mensuel'), ('view_statistiques', 'Voir les statistiques'), ('export_data', 'Exporter les données'), ('manage_users', 'Gérer les utilisateurs'), ('manage_permissions', 'Gérer les permissions'), ('manage_system', 'Gérer le système')], max_length=50, unique=True),
        ),
    ]
