# Generated by Django 5.2.5 on 2025-11-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_remove_historicaltarifservice_produit_consomme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recettemultiservice',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='recettemultiservice',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='historicaltarifservice',
            name='type_papier',
        ),
        migrations.RemoveField(
            model_name='tarifservice',
            name='type_papier',
        ),
        migrations.DeleteModel(
            name='RecetteInternet',
        ),
        migrations.DeleteModel(
            name='RecetteMultiservice',
        ),
    ]
