# Generated by Django 5.2.5 on 2025-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_remove_recettemultiservice_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Cyber', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('default_currency', models.CharField(default='Ar', help_text='Devise par défaut (ex: Ar, EUR, USD)', max_length=10)),
                ('default_stock_alert_threshold', models.DecimalField(decimal_places=2, default=5, help_text="Seuil d'alerte de stock par défaut pour les nouveaux produits", max_digits=10)),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
    ]
